# Generated by Django 3.2.20 on 2023-07-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
